### ISSUE TITLE
website cleanup

### ISSUE THREAD

**Issue by saisivam** [bhagavad-gita/bhagavad-gita.github.io#1]
remove news
replace media with classes in all pages
replace volunteer with internship page
hide donate page
hide trust page
replace the contact details
with 
Bhagavad-gita Today, Chennai
Chennai Office Address

**Comment by saisivam** [comment]
sekar, please take care of the website. thanks.

**Comment by srilasekar** [comment]
removed news links

**Comment by srilasekar** [comment]
removed donate link

**Comment by srilasekar** [comment]
change name on contact

**Comment by srilasekar** [comment]
add mail address

**Comment by srilasekar** [comment]
add website

**Comment by srilasekar** [comment]
changed mail and website address

**Comment by srilasekar** [comment]
changed map link for new address

**Comment by srilasekar** [comment]
changed address of location

**Comment by srilasekar** [comment]
replaced valunteer with internships

**Comment by srilasekar** [comment]
replaced media with classes to all page
