### ISSUE TITLE
homepage cleanup

### ISSUE THREAD

**Issue by saisivam** [bhagavad-gita/bhagavad-gita.github.io#2]
remove timings
remove sunday program
remove youtube video
remove quote of sp

**Comment by srilasekar** [comment]
Removed Timing in index page

**Comment by srilasekar** [comment]
Removed sunday agenta in index age

**Comment by srilasekar** [comment]
Removed youtube video link

**Comment by srilasekar** [comment]
Removed quotes in index page

**Comment by srilasekar** [comment]
All done.
