### ISSUE TITLE
internship page cleanup

### ISSUE THREAD

**Issue by saisivam** [bhagavad-gita/bhagavad-gita.github.io#3]
Internship 1 
Topic: Text Analytics in Ancient Indian Scriptures
Technologies: Python, Hadoop 2, 
	SPARK, Map Reduce, Data Structures,
     and Text Processing Algorithm

Internship 2
Topic: Storage and Retrieval of Ancient Indian Scriptures
     
Technologies: Python, Linux, Cloud, OpenStack, EC2, Rackspace, CentOS,
     HDFS, Hadoop 2, Flume, RDBMS, Hive

Internship 3
Topic: Visualisation of Text Analytics in Ancient Indian Scripture
     
Technologies: Python, Hadoop 2, Map Reduce, MVC Architecture, Django

Contact:

Dinesh Thirumurthy

**Comment by srilasekar** [comment]
Internship page edited.

**Comment by srilasekar** [comment]
All done

**Comment by saisivam** [comment]
remove leading para.
remove the facebook like and sign up stuff. 
Title should be Internships

**Comment by srilasekar** [comment]
Removed FB links in Internships page

**Comment by srilasekar** [comment]
Removed leading para

**Comment by srilasekar** [comment]
Edited contact to big font and red

**Comment by srilasekar** [comment]
Edited Title

**Comment by srilasekar** [comment]
All done.
