### ISSUE TITLE
move philosophy to second position in navbar

### ISSUE THREAD

**Issue by saisivam** [bhagavad-gita/bhagavad-gita.github.io#8]
add bio of srila prabhupada
add pics of srila prabhupada
add a video of srila prabhupada

**Comment by saisivam** [comment]
images link

https://www.google.com/search?q=srila+prabhupada

**Comment by srilasekar** [comment]
Working on it, will complete on today

**Comment by dvenkatesan1968** [comment]
sekar,

how to it see the Gita text you added to GitHub?
regards,


On Mon, Jan 26, 2015 at 7:25 AM, srilasekar <notifications@github.com>
wrote:

> Working on it, will complete on today
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhagavad-gita/bhagavad-gita.github.io/issues/8#issuecomment-71405996>
> .
>



-- 
Prof.D.Venkatesan
HOD, Department of IT/CSE
BIT Campus,
Anna University - Regional Centre
Tiruchirapalli - 620024
Mobile: 09150903401, 09976906268
Land: 0431- 2407990

**Comment by srilasekar** [comment]
Moved philosophy to second position

**Comment by saisivam** [comment]
gita slokas will be available after this milestone M1

**Comment by saisivam** [comment]
added a link to the wikipedia entry as bio

**Comment by saisivam** [comment]
added a link to google images search results for pictures

**Comment by saisivam** [comment]
embedded a youtube video on srila prabhupada's famous tv interview

**Comment by saisivam** [comment]
separating tickets for srila prabhupada's classes and lectures

**Comment by saisivam** [comment]
all done.

**Comment by saisivam** [comment]
closing ticket.
